### ISSUE TITLE
feature-request: Open search results in separate page

### ISSUE THREAD

**Issue by chancez** [cilium/cilium.io#201] opened 2022-11-28 17:03 UTC
Currently when searching on the cilium blog, the results are displayed in a small list pop-up in the page, and has an option to "expand" to see more. Ideally we would also offer an option to open the results in a new page, which would be easier to look for results in.

**Comment by kayceeDev** [comment] 2023-02-03 09:40
@chancez if I understand you correctly, you want a "See more button" that takes the user to another page containing the blogs that match the search results right?

While this is great, what is the intention of this feature? Does it help the UX since there is already a "View All" button in the pop-up? 

If there is still a need, will these returned search results be paginated on the new page assuming it is too long?

While the new page also contains another search box assuming the user what to filter from the originally filtered result. will it have a filter by-tag button like in the "All posts" sections?

**Comment by chancez** [comment] 2023-02-03 16:58
The intent is that it's easier to view results as I mentioned. Trying to view the search results in the tiny drop down is pretty bad UX when trying to look through a large list of search results. 

This isn't a novel idea or anything, this UX pattern is pretty well established, I'm not sure I need to come up with reasons why having the ability to view search results in another page is a good idea.

**Comment by kayceeDev** [comment] 2023-02-03 17:29
> The intent is that it's easier to view results as I mentioned. Trying to view the search results in the tiny drop down is pretty bad UX when trying to look through a large list of search results.

Alright. I will like to take a dig at this.

**Comment by divz-codess** [comment] 2023-02-12 19:25
Hi @xmulligan @kayceeDev @chancez I had an idea to expand the search bar upon being clicked and collapse options on the right (Enterprise, Learn, etc.) into a drop-down and again contract the search bar after search completion. If that sounds alright?

**Comment by xmulligan** [comment] 2023-02-20 11:28
@divz-codess do you mean on docs.cilium.io or on cilium.io?

**Comment by divz-codess** [comment] 2023-02-20 21:35
@xmulligan the issue is at https://cilium.io/blog/ so I meant to change it there.

**Comment by Shubhamlmp** [comment] 2023-02-22 20:13
Hi @chancez I think what I find the solution for this problem is instead of expanding search bar and this small drop down. when user click on search button we can open a full page size search modal.
Please let me know if it is okay for you?

**Comment by xmulligan** [comment] 2023-02-23 09:16
I think @chancez was looking for what @Shubhamlmp wrote

**Comment by Shubhamlmp** [comment] 2023-02-23 18:22
@chancez @xmulligan So, can I do some r&d on this and start working?

**Comment by divz-codess** [comment] 2023-02-23 18:41
@chancez @xmulligan I think that having a modal only for searching blogs isn't much needed as at the end we are just displaying the blog titles and a short description so a modal dedicated for searching won't be required. 
Your opinions are most welcome :)

**Comment by Neilblaze** [comment] 2023-03-03 13:04
Been following some design patterns for a while, & after a few iterations, I came up with this 👇🏼 

**Current**            |  **New (proposed)**
:-------------------------:|:-------------------------:
![current_cilium](https://user-images.githubusercontent.com/48355572/222723184-399795a3-5e5a-4819-a3d8-f30a17253034.png)  |  ![new_cilium](https://user-images.githubusercontent.com/48355572/222723255-be6b2430-8abb-44c5-a5b1-979da6703fa4.png)

I've crafted it in a way that maintains the overall UX consistency of the website making it a perfect fit! I do believe that it'll look even better in **`dark-mode`** if it's added to the [blog](https://cilium.io/blog) in near future.

> "...option to open the results in a new page, which would be easier to look for results in."

The updated search solves the above issue. One just needs to click on the "open in a new tab" button <img src="https://user-images.githubusercontent.com/48355572/222726664-140bd1cf-fb29-4fd5-8926-d659c4632ea7.png" width="12px" height="12px"> to open that particular link in a new tab. Additionally, I've proposed a few more features in the same which will help maintainers & active users keep a track of the `page-visits`. Plus, one can even opt to share the link with anyone or copy the source link to the clipboard with just a simple click!


cc: @chancez, @xmulligan

**Comment by xmulligan** [comment] 2023-03-07 14:21
@Neilblaze I think @chancez was asking for something slightly different. When searching, he wants all of the results to open in a new page not being able to open individual results on a new page. Does that make sense?

**Comment by Neilblaze** [comment] 2023-03-07 15:02
Makes sense now. So, that simply means, *clicking* on the *search button* <img src="https://user-images.githubusercontent.com/48355572/223460392-d426f188-fede-4b41-8a99-914c5f25a555.png" width="12px" height="12px"> will redirect the user to a new `../search` page, and the rest will be just as it is, correct? @xmulligan

**Comment by xmulligan** [comment] 2023-11-29 14:35
I think we can close this with #404

**Closed by xmulligan** 2023-11-29 14:35 UTC
